CREATE TABLE tb_fornecedor_victor(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    nome varchar(64),
    descricao varchar(128),
    id_categoria integer,
    id_moeda integer,
    id_marca integer,
    id_cores integer,
    id_unidade_medida integer,
    id_grupo integer,
    preco_compra numeric(12,2),
    preco_venda numeric(12,2),
    PRIMARY KEY(id),
    CONSTRAINT fk_categoria FOREIGN key(id_categoria) REFERENCES tb_categoria(id),
    CONSTRAINT fk_moeda FOREIGN key(id_moeda) REFERENCES tb_moeda(id),
    CONSTRAINT fk_marca FOREIGN key(id_marca) REFERENCES tb_marca(id),
    CONSTRAINT fk_cores FOREIGN key(id_cores) REFERENCES tb_cores(id),
    CONSTRAINT fk_unidade_medida FOREIGN key(id_unidade_medida) REFERENCES tb_medida(id),
    CONSTRAINT fk_grupo FOREIGN key(id_grupo) REFERENCES tb_grupo(id)
);
